# this action: https://github.com/marketplace/actions/version-bumper
# also see the options file for configuration
name: Manage versions

# not actually on all pushes, see the options file
on: [push]

jobs:
  bump:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout action is required
      - uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.DMITRY_PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Bump Versions
        uses: michmich112/version-bumper@master
        with:
          options-file: "./.github/version_bump_options.json"
          github-token: ${{ secrets.DMITRY_PAT }}
