# this action: https://github.com/marketplace/actions/version-bumper
# also see the options file for configuration
name: Manage versions

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  bump:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout action is required
      - uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.DMITRY_PAT }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Change version number
        id: version
        run: |
          python -m pip install bump2version
          if [[ "${{ GITHUB_EVENT_NAME }}" == "pull_request"* ]]; then
            branch=$(echo "${{ GITHUB_BASE_REF }}")
          else
            branch=$(echo "${{ GITHUB_REF_NAME }}")
          fi
          if [[ $branch == "main" ]]; then
            version="minor"
          else
            version="patch"
          fi
          bump2version $version --commit --message "Bump version: {current_version} → {new_version}" --allow-dirty
          git push
