name: Release Helper

on:
  push:
    branches:
      - main

jobs:
  sync_dev:
    needs: correct_repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: dev
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Reset dev branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create pull request into dev
        uses: peter-evans/create-pull-request@v3
        with:
          branch: bot/sync-main-dev
          commit-message: "chore: sync main-dev"
          base: dev
          title: "chore: sync main->dev"
          labels: chore
          body: |
            Syncing Main->Dev.
